//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 10:56:24 PM MSK 
//


package by.it.zagurskaya.jd02_09.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Currency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Currency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idCurrency" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="receivedCurrency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="comingCurrency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="spendingCurrency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="hendedCurrency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="balanceCarrency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Currency", propOrder = {
    "idCurrency",
    "receivedCurrency",
    "comingCurrency",
    "spendingCurrency",
    "hendedCurrency",
    "balanceCarrency"
})
public class Currency {

    @XmlElement(required = true)
    protected BigInteger idCurrency;
    protected double receivedCurrency;
    protected double comingCurrency;
    protected double spendingCurrency;
    protected double hendedCurrency;
    protected double balanceCarrency;

    /**
     * Gets the value of the idCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdCurrency() {
        return idCurrency;
    }

    /**
     * Sets the value of the idCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdCurrency(BigInteger value) {
        this.idCurrency = value;
    }

    /**
     * Gets the value of the receivedCurrency property.
     * 
     */
    public double getReceivedCurrency() {
        return receivedCurrency;
    }

    /**
     * Sets the value of the receivedCurrency property.
     * 
     */
    public void setReceivedCurrency(double value) {
        this.receivedCurrency = value;
    }

    /**
     * Gets the value of the comingCurrency property.
     * 
     */
    public double getComingCurrency() {
        return comingCurrency;
    }

    /**
     * Sets the value of the comingCurrency property.
     * 
     */
    public void setComingCurrency(double value) {
        this.comingCurrency = value;
    }

    /**
     * Gets the value of the spendingCurrency property.
     * 
     */
    public double getSpendingCurrency() {
        return spendingCurrency;
    }

    /**
     * Sets the value of the spendingCurrency property.
     * 
     */
    public void setSpendingCurrency(double value) {
        this.spendingCurrency = value;
    }

    /**
     * Gets the value of the hendedCurrency property.
     * 
     */
    public double getHendedCurrency() {
        return hendedCurrency;
    }

    /**
     * Sets the value of the hendedCurrency property.
     * 
     */
    public void setHendedCurrency(double value) {
        this.hendedCurrency = value;
    }

    /**
     * Gets the value of the balanceCarrency property.
     * 
     */
    public double getBalanceCarrency() {
        return balanceCarrency;
    }

    /**
     * Sets the value of the balanceCarrency property.
     * 
     */
    public void setBalanceCarrency(double value) {
        this.balanceCarrency = value;
    }

}
