//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 10:56:24 PM MSK 
//


package by.it.zagurskaya.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Description complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Description">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operations" type="{http://beans.jd02_09.zagurskaya.it.by/}Operations"/>
 *         &lt;element name="kassa" type="{http://beans.jd02_09.zagurskaya.it.by/}Kassa"/>
 *         &lt;element name="duties" type="{http://beans.jd02_09.zagurskaya.it.by/}Duties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Description", propOrder = {
    "operations",
    "kassa",
    "duties"
})
public class Description {

    @XmlElement(required = true)
    protected Operations operations;
    @XmlElement(required = true)
    protected Kassa kassa;
    @XmlElement(required = true)
    protected Duties duties;

    /**
     * Gets the value of the operations property.
     * 
     * @return
     *     possible object is
     *     {@link Operations }
     *     
     */
    public Operations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operations }
     *     
     */
    public void setOperations(Operations value) {
        this.operations = value;
    }

    /**
     * Gets the value of the kassa property.
     * 
     * @return
     *     possible object is
     *     {@link Kassa }
     *     
     */
    public Kassa getKassa() {
        return kassa;
    }

    /**
     * Sets the value of the kassa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kassa }
     *     
     */
    public void setKassa(Kassa value) {
        this.kassa = value;
    }

    /**
     * Gets the value of the duties property.
     * 
     * @return
     *     possible object is
     *     {@link Duties }
     *     
     */
    public Duties getDuties() {
        return duties;
    }

    /**
     * Sets the value of the duties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duties }
     *     
     */
    public void setDuties(Duties value) {
        this.duties = value;
    }

}
