//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 07:29:05 PM EAT 
//


package by.it.zagurskaya.jd02_09.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idEntry" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nameEntry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currencyEntry" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="accauntDebitEntry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accauntKreditEntry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sumEntry" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="comingOrSpeting" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rateEntry" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", propOrder = {
    "idEntry",
    "nameEntry",
    "currencyEntry",
    "accauntDebitEntry",
    "accauntKreditEntry",
    "sumEntry",
    "comingOrSpeting",
    "rateEntry"
})
public class Entry {

    @XmlElement(required = true)
    protected BigInteger idEntry;
    @XmlElement(required = true)
    protected String nameEntry;
    @XmlElement(required = true)
    protected BigInteger currencyEntry;
    @XmlElement(required = true)
    protected String accauntDebitEntry;
    @XmlElement(required = true)
    protected String accauntKreditEntry;
    protected double sumEntry;
    protected boolean comingOrSpeting;
    protected double rateEntry;

    /**
     * Gets the value of the idEntry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdEntry() {
        return idEntry;
    }

    /**
     * Sets the value of the idEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdEntry(BigInteger value) {
        this.idEntry = value;
    }

    /**
     * Gets the value of the nameEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEntry() {
        return nameEntry;
    }

    /**
     * Sets the value of the nameEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEntry(String value) {
        this.nameEntry = value;
    }

    /**
     * Gets the value of the currencyEntry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrencyEntry() {
        return currencyEntry;
    }

    /**
     * Sets the value of the currencyEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrencyEntry(BigInteger value) {
        this.currencyEntry = value;
    }

    /**
     * Gets the value of the accauntDebitEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccauntDebitEntry() {
        return accauntDebitEntry;
    }

    /**
     * Sets the value of the accauntDebitEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccauntDebitEntry(String value) {
        this.accauntDebitEntry = value;
    }

    /**
     * Gets the value of the accauntKreditEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccauntKreditEntry() {
        return accauntKreditEntry;
    }

    /**
     * Sets the value of the accauntKreditEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccauntKreditEntry(String value) {
        this.accauntKreditEntry = value;
    }

    /**
     * Gets the value of the sumEntry property.
     * 
     */
    public double getSumEntry() {
        return sumEntry;
    }

    /**
     * Sets the value of the sumEntry property.
     * 
     */
    public void setSumEntry(double value) {
        this.sumEntry = value;
    }

    /**
     * Gets the value of the comingOrSpeting property.
     * 
     */
    public boolean isComingOrSpeting() {
        return comingOrSpeting;
    }

    /**
     * Sets the value of the comingOrSpeting property.
     * 
     */
    public void setComingOrSpeting(boolean value) {
        this.comingOrSpeting = value;
    }

    /**
     * Gets the value of the rateEntry property.
     * 
     */
    public double getRateEntry() {
        return rateEntry;
    }

    /**
     * Sets the value of the rateEntry property.
     * 
     */
    public void setRateEntry(double value) {
        this.rateEntry = value;
    }

}
