//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 07:29:05 PM EAT 
//


package by.it.zagurskaya.jd02_09.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Operation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idOperation" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nameOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="printForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="skreanForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="specification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entrys" type="{http://beans.jd02_09.zagurskaya.it.by/}Entrys"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Operation", propOrder = {
    "idOperation",
    "nameOperation",
    "printForm",
    "skreanForm",
    "specification",
    "entrys"
})
public class Operation {

    @XmlElement(required = true)
    protected BigInteger idOperation;
    @XmlElement(required = true)
    protected String nameOperation;
    @XmlElement(required = true)
    protected String printForm;
    @XmlElement(required = true)
    protected String skreanForm;
    @XmlElement(required = true)
    protected String specification;
    @XmlElement(required = true)
    protected Entrys entrys;

    /**
     * Gets the value of the idOperation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdOperation() {
        return idOperation;
    }

    /**
     * Sets the value of the idOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdOperation(BigInteger value) {
        this.idOperation = value;
    }

    /**
     * Gets the value of the nameOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOperation() {
        return nameOperation;
    }

    /**
     * Sets the value of the nameOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOperation(String value) {
        this.nameOperation = value;
    }

    /**
     * Gets the value of the printForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintForm() {
        return printForm;
    }

    /**
     * Sets the value of the printForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintForm(String value) {
        this.printForm = value;
    }

    /**
     * Gets the value of the skreanForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkreanForm() {
        return skreanForm;
    }

    /**
     * Sets the value of the skreanForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkreanForm(String value) {
        this.skreanForm = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecification(String value) {
        this.specification = value;
    }

    /**
     * Gets the value of the entrys property.
     * 
     * @return
     *     possible object is
     *     {@link Entrys }
     *     
     */
    public Entrys getEntrys() {
        return entrys;
    }

    /**
     * Sets the value of the entrys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entrys }
     *     
     */
    public void setEntrys(Entrys value) {
        this.entrys = value;
    }

}
