//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.14 at 07:10:55 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beans.jd02_09.lyakhova.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.lyakhova.jd02_09.beans;
