//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.17 at 03:39:32 PM MSK 
//


package by.it.yarmolenka.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="actual_bet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odds" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="actual_result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bet_amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="payout" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bet", propOrder = {
    "sport",
    "event",
    "actualBet",
    "odds",
    "actualResult",
    "betAmount",
    "payout"
})
public class Bet {

    @XmlElement(required = true)
    protected String sport;
    @XmlElement(required = true)
    protected String event;
    @XmlElement(name = "actual_bet", required = true)
    protected String actualBet;
    protected double odds;
    @XmlElement(name = "actual_result", required = true)
    protected String actualResult;
    @XmlElement(name = "bet_amount")
    protected double betAmount;
    protected double payout;

    /**
     * Gets the value of the sport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSport() {
        return sport;
    }

    /**
     * Sets the value of the sport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSport(String value) {
        this.sport = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the actualBet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualBet() {
        return actualBet;
    }

    /**
     * Sets the value of the actualBet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualBet(String value) {
        this.actualBet = value;
    }

    /**
     * Gets the value of the odds property.
     * 
     */
    public double getOdds() {
        return odds;
    }

    /**
     * Sets the value of the odds property.
     * 
     */
    public void setOdds(double value) {
        this.odds = value;
    }

    /**
     * Gets the value of the actualResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualResult() {
        return actualResult;
    }

    /**
     * Sets the value of the actualResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualResult(String value) {
        this.actualResult = value;
    }

    /**
     * Gets the value of the betAmount property.
     * 
     */
    public double getBetAmount() {
        return betAmount;
    }

    /**
     * Sets the value of the betAmount property.
     * 
     */
    public void setBetAmount(double value) {
        this.betAmount = value;
    }

    /**
     * Gets the value of the payout property.
     * 
     */
    public double getPayout() {
        return payout;
    }

    /**
     * Sets the value of the payout property.
     * 
     */
    public void setPayout(double value) {
        this.payout = value;
    }

}
