//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.17 at 03:39:32 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jd02_09.yarmolenka.it.by/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.yarmolenka.jd02_09.beans;
