//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 11:16:02 AM MSK 
//


package by.it.titkovskaya.jd02.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authorization_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="account_balance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="last_replenishment" type="{http://beans.jd02_09.titkovskaya.it.by/}Replenishment"/>
 *         &lt;element name="last_payment" type="{http://beans.jd02_09.titkovskaya.it.by/}Payment"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lock_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account", propOrder = {
    "accountID",
    "authorizationCode",
    "accountBalance",
    "currency",
    "lastReplenishment",
    "lastPayment",
    "status",
    "lockDate"
})
public class Account {

    @XmlElement(name = "account_ID", required = true)
    protected String accountID;
    @XmlElement(name = "authorization_code", required = true)
    protected String authorizationCode;
    @XmlElement(name = "account_balance")
    protected double accountBalance;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(name = "last_replenishment", required = true)
    protected Replenishment lastReplenishment;
    @XmlElement(name = "last_payment", required = true)
    protected Payment lastPayment;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "lock_date", required = true)
    protected String lockDate;

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the authorizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Sets the value of the authorizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationCode(String value) {
        this.authorizationCode = value;
    }

    /**
     * Gets the value of the accountBalance property.
     * 
     */
    public double getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     * 
     */
    public void setAccountBalance(double value) {
        this.accountBalance = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the lastReplenishment property.
     * 
     * @return
     *     possible object is
     *     {@link Replenishment }
     *     
     */
    public Replenishment getLastReplenishment() {
        return lastReplenishment;
    }

    /**
     * Sets the value of the lastReplenishment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Replenishment }
     *     
     */
    public void setLastReplenishment(Replenishment value) {
        this.lastReplenishment = value;
    }

    /**
     * Gets the value of the lastPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getLastPayment() {
        return lastPayment;
    }

    /**
     * Sets the value of the lastPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setLastPayment(Payment value) {
        this.lastPayment = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the lockDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockDate() {
        return lockDate;
    }

    /**
     * Sets the value of the lockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockDate(String value) {
        this.lockDate = value;
    }

    @Override
    public String toString() {
        return "\n\t\t\tAccount{" +
                "\n\t\t\t\taccountID='" + accountID + '\'' +
                ", \n\t\t\t\tauthorizationCode='" + authorizationCode + '\'' +
                ", \n\t\t\t\taccountBalance=" + accountBalance +
                ", \n\t\t\t\tcurrency='" + currency + '\'' +
                ", \n\t\t\t\tlastReplenishment=" + lastReplenishment +
                ", \n\t\t\t\tlastPayment=" + lastPayment +
                ", \n\t\t\t\tstatus='" + status + '\'' +
                ", \n\t\t\t\tlockDate='" + lockDate.trim() + '\'' +
                "\n\t\t\t}";
    }
}
