//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 11:16:02 AM MSK 
//


package by.it.titkovskaya.jd02.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Replenishment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Replenishment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="replenishment_amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="replenishment_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Replenishment", propOrder = {
    "replenishmentAmount",
    "replenishmentDate"
})
public class Replenishment {

    @XmlElement(name = "replenishment_amount")
    protected double replenishmentAmount;
    @XmlElement(name = "replenishment_date", required = true)
    protected String replenishmentDate;

    /**
     * Gets the value of the replenishmentAmount property.
     * 
     */
    public double getReplenishmentAmount() {
        return replenishmentAmount;
    }

    /**
     * Sets the value of the replenishmentAmount property.
     * 
     */
    public void setReplenishmentAmount(double value) {
        this.replenishmentAmount = value;
    }

    /**
     * Gets the value of the replenishmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplenishmentDate() {
        return replenishmentDate;
    }

    /**
     * Sets the value of the replenishmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplenishmentDate(String value) {
        this.replenishmentDate = value;
    }

    @Override
    public String toString() {
        return "Replenishment{" +
                "\n\t\t\t\t\treplenishmentAmount=" + replenishmentAmount +
                ", \n\t\t\t\t\treplenishmentDate='" + replenishmentDate.trim() + '\'' +
                "}";
    }
}
